services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: egc_cloudflared
    command: tunnel --no-autoupdate --url ${TUNNEL_ORIGIN:-http://host.docker.internal:8080}
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
